# Site settings
title: OpSec for Journalists
email: jmp@opsec.press
description: "\"Journalism is publishing what someone else doesn't want published; all the rest is public relations.\"\n--George Orwell"
baseurl: ""
url: "https://opsec.press"
twitter_username: toholdaquill
github_username:  JMPorup

# Build settings
markdown: kramdown
permalink: pretty
